# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileView(object):
    def setupUi(self, FileView):
        FileView.setObjectName("FileView")
        FileView.resize(900, 600)
        FileView.setMinimumSize(QtCore.QSize(900, 600))
        FileView.setMaximumSize(QtCore.QSize(900, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        FileView.setFont(font)
        FileView.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FileView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uploadDisplay = QtWidgets.QLineEdit(FileView)
        self.uploadDisplay.setReadOnly(True)
        self.uploadDisplay.setObjectName("uploadDisplay")
        self.horizontalLayout.addWidget(self.uploadDisplay)
        self.saveBtn = QtWidgets.QPushButton(FileView)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.fileBrowser = QtWidgets.QTextBrowser(FileView)
        self.fileBrowser.setReadOnly(False)
        self.fileBrowser.setObjectName("fileBrowser")
        self.verticalLayout_2.addWidget(self.fileBrowser)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(FileView)
        QtCore.QMetaObject.connectSlotsByName(FileView)

    def retranslateUi(self, FileView):
        _translate = QtCore.QCoreApplication.translate
        FileView.setWindowTitle(_translate("FileView", "查看/编辑试卷"))
        self.saveBtn.setText(_translate("FileView", "保存文件"))
import resources_rc
