# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessView(object):
    def setupUi(self, ProcessView):
        ProcessView.setObjectName("ProcessView")
        ProcessView.resize(900, 600)
        ProcessView.setMinimumSize(QtCore.QSize(900, 600))
        ProcessView.setMaximumSize(QtCore.QSize(900, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        ProcessView.setFont(font)
        ProcessView.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveBtn = QtWidgets.QPushButton(ProcessView)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.processBrowser = QtWidgets.QTextBrowser(ProcessView)
        self.processBrowser.setReadOnly(True)
        self.processBrowser.setObjectName("processBrowser")
        self.verticalLayout_2.addWidget(self.processBrowser)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(ProcessView)
        QtCore.QMetaObject.connectSlotsByName(ProcessView)

    def retranslateUi(self, ProcessView):
        _translate = QtCore.QCoreApplication.translate
        ProcessView.setWindowTitle(_translate("ProcessView", "查看语法分析过程"))
        self.saveBtn.setText(_translate("ProcessView", "保存分析过程"))
import resources_rc
