
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANSWER HEADER OPTION QUESTION QUESTIONHEADERpaper : HEADER questionheadersquestionheaders : questionheader questionheaders\n                        | questionheaderquestionheader : QUESTIONHEADER questionsquestions : question questions\n                    | questionquestion : QUESTION\n                    | QUESTION options\n                    | QUESTION answer\n                    | QUESTION options answeranswer : ANSWERoptions : OPTION options\n               | OPTION'
    
_lr_action_items = {'HEADER':([0,],[2,]),'$end':([1,3,4,6,7,8,9,10,11,12,13,14,15,16,],[0,-1,-3,-2,-4,-6,-7,-5,-8,-9,-13,-11,-10,-12,]),'QUESTIONHEADER':([2,4,7,8,9,10,11,12,13,14,15,16,],[5,5,-4,-6,-7,-5,-8,-9,-13,-11,-10,-12,]),'QUESTION':([5,8,9,11,12,13,14,15,16,],[9,9,-7,-8,-9,-13,-11,-10,-12,]),'OPTION':([9,13,],[13,13,]),'ANSWER':([9,11,13,16,],[14,14,-13,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'paper':([0,],[1,]),'questionheaders':([2,4,],[3,6,]),'questionheader':([2,4,],[4,4,]),'questions':([5,8,],[7,10,]),'question':([5,8,],[8,8,]),'options':([9,13,],[11,16,]),'answer':([9,11,],[12,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> paper","S'",1,None,None,None),
  ('paper -> HEADER questionheaders','paper',2,'p_paper','examSP.py',34),
  ('questionheaders -> questionheader questionheaders','questionheaders',2,'p_questionheaders','examSP.py',38),
  ('questionheaders -> questionheader','questionheaders',1,'p_questionheaders','examSP.py',39),
  ('questionheader -> QUESTIONHEADER questions','questionheader',2,'p_questionheader','examSP.py',46),
  ('questions -> question questions','questions',2,'p_questions','examSP.py',50),
  ('questions -> question','questions',1,'p_questions','examSP.py',51),
  ('question -> QUESTION','question',1,'p_question','examSP.py',58),
  ('question -> QUESTION options','question',2,'p_question','examSP.py',59),
  ('question -> QUESTION answer','question',2,'p_question','examSP.py',60),
  ('question -> QUESTION options answer','question',3,'p_question','examSP.py',61),
  ('answer -> ANSWER','answer',1,'p_answer','examSP.py',70),
  ('options -> OPTION options','options',2,'p_options','examSP.py',78),
  ('options -> OPTION','options',1,'p_options','examSP.py',79),
]
